### ISSUE TITLE
Google drive files create backpressuring and piping

### ISSUE THREAD

**Issue by cyrilchapon** [googleapis/nodejs-googleapis-common#72] opened 2019-01-11 12:30 UTC
#### Environment details

  - OS: Mac OS high sierra
  - Node.js version: 9.5.0
  - npm version:6.0.1
  - `googleapis-common` version: 0.4.0 (through googleapis 36.0.0)

#### Description

I'm trying to proxy a file upload from a frontend to google drive through a node.js server.

In the frontend, I'm using Axios to send a multipart request like so 

```
export const uploadFileGdriveThroughBackend = (fileDescriptor, options) => {
  const data = new window.FormData()
  data.append('file', fileDescriptor, fileDescriptor.name)

  return axios.post(`/api/v1/file`, data, {
    ...options,
    headers: {
      'Content-Type': `multipart/form-data; boundary=${data._boundary}`
    }
  })
}
```

In the backend, I'm using multer to intercept multipart request and pipe the file upload stream to `googleapis`, like so :

```
const gapi = require('googleapis')

class GoogleDriveMulterStorage {
  constructor (jwtClient, createFileOptions) {
    if (!jwtClient || !(jwtClient instanceof gapi.google.auth.JWT)) {
      throw new Error('jwtClient should be a googleapis.google.auth.JWT instance')
    }

    this._jwtClient = jwtClient
    this._drive = gapi.google.drive({
      version: 'v3',
      auth: this._jwtClient
    })
    this._createFileOptions = createFileOptions
      ? ((typeof createFileOptions === 'function')
        ? createFileOptions
        : () => createFileOptions)
      : () => ({})
  }

  async __handleFile (req, file) {
    const customOptions = await this._createFileOptions(req, file)

    return this._drive.files.create({
      supportsTeamDrives: true,
      ...customOptions,
      requestBody: {
        name: file.originalname,
        mimeType: file.mimetype,
        ...customOptions.requestBody
      },
      media: {
        body: file.stream, // ==> Here, as suggested by googleapis doc
        mimeType: file.mimetype,
        ...customOptions.media
      }
    })
  }

  _handleFile (req, file, cb) {
    this.__handleFile(req, file)
      .then(res => cb(null, {
        id: res.data.id,
        kind: res.data.kind
      }))
      .catch(err => cb(err))
  }

  _removeFile (req, file, cb) {}
}

module.exports = GoogleDriveMulterStorage
```

The issue I'm facing is that the real data upload (frontend => backend) of a file is way faster than the subsequent upload (backend => google API), which is normal but introduce a strange behavior.

When I'm binding to the `onUploadProgress` *on the frontend axios* (don't mix ith internal googleapis-common axios), I see a fast progress; but the server response come very later from my backend. This is because `multer` does send HTTP response after all file streams (only one in my case) are correctly ended and closed before passing to the next middleware. For the sake of information, be aware that this is not multer-related, since I tried to do the same manualy with busboy (not returning the response on 'finish' event but rather on 'end' of the last-file re-upload stream)

I feel like this is not normal, because : if my frontend tells me "the upload progress is 70, 80 then 100%" and 10 seconds later tells me "response received", this is because my backend is "storing" the uploaded data somewhere (buffering, actualy), which is a big problem when sending laaarge file.

What would be a better workflow in my mind : "pausing" the upload (frontend => backend) stream while waiting along with the re-upload (backend => google) stream chunk by chunk.

I think this is what we call ["backpressure"](https://nodejs.org/en/docs/guides/backpressuring-in-streams/) in node.js, and I suspect the strategy adopted [HERE](https://github.com/googleapis/nodejs-googleapis-common/blob/master/src/apirequest.ts#L186-L209) is not compliant with this concept.

I'm a real noob with streams and even more wit HTTP streams so, Am I right ? If yes, is that wanted ? If yes, is that someting I can control ?

Thanks for your help

**Comment by AVaksman** [comment] 2019-01-22 05:16
@cyrilchapon 
The default behavior is that streaming request is fully buffered then uploaded gradually.
This can be changed by setting `maxRedirects` to 0 in the request. This will allow gradual read => upload behavior. 
So your code will look something like this,
```javascript
  async __handleFile(req, file) {
    const customOptions = await this._createFileOptions(req, file);

    return this._drive.files.create(
      {
        supportsTeamDrives: true,
        ...customOptions,
        requestBody: {
          name: file.originalname,
          mimeType: file.mimetype,
          ...customOptions.requestBody
        },
        media: {
          body: file.stream, // ==> Here, as suggested by googleapis doc
          mimeType: file.mimetype,
          ...customOptions.media
        }
      },
      {
        maxRedirects: 0
      }
    );
  }
```
:exclamation: Please note, there was an issue with partial data lose while using this setting. The issue is fixed with PR #67 and will be available with next release.

**Comment by cyrilchapon** [comment] 2019-01-22 10:07
Fantastic, but 2 questions :
- Why is that relative to maxRedirects ?
- Where is it documented ?

Thanks bud :)

**Comment by AVaksman** [comment] 2019-01-22 14:54
`maxRedirects` is an Axios feature. It is discussed [here](https://github.com/axios/axios/issues/1045).

**Comment by cyrilchapon** [comment] 2019-01-22 15:45
Oh okay. Great.

Thanks you saving my week :)

**Comment by cyrilchapon** [comment] 2019-01-23 08:15
Duplicate of https://github.com/googleapis/google-api-nodejs-client/issues/1354
And indeed underlying issue here https://github.com/axios/axios/issues/1045

Though I suggest leaving this open until axios fixes it, because this behavior directly impacts googleapis.drive

Furthermore, wouldn't it be preferable to force `maxRedirect` *inside googleapi axios call* (default option) in the meantime ?

As an API consumer, even if one understand that underlying issue and the fact googleapis is using axios as an internal lib; the truth is : gape.drive.files.create just doesn't handle backpressuring correctly by default.

**Comment by JustinBeckwith** [comment] 2019-01-30 21:42
Greetings!  I think we fixed this in the latest release (v37) of googleapis.  Can you give it a shot and see if you still run into problems?

**Closed by JustinBeckwith** 2019-01-30 21:42 UTC
Labels: :rotating_light:, triage me

**Comment by cyrilchapon** [comment] 2019-02-15 19:16
@JustinBeckwith we pulled and implemented with the axios option. It just works 👍
